package:
  name: cypico
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - numpy 1.9.0
    - cython 0.21

  run:
    - python
    - numpy 1.9.0

test:
  imports:
  - cypico

about:
  home: https://github.com/menpo/cypico/
  license: BSD
